# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e7a756eeca961b76151c247e1f628a4c4fcea756d2fe4880f63d520b4758032bfb1df709117adf577232f35574b1b111dc7872674a0daadb6a93bf5fbaeaee5

test:
  secret_key_base: 0df2b4a1d0c386a73029e8ed3f463a40547f0ea33ba681f3be1a18b171733c16ad2c9b09f5bfef6ff41d330d67f449d95ed3bb2deeaed43531ddb3050ccd0153

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
